### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by ghost** [npc-engine/npc-engine#65]
After a pip install I try 
npc-engine run --models-path models --port 5555

I am greeted with 

Traceback (most recent call last):
  File "/home/lucky/miniconda3/envs/npc-engine/bin/npc-engine", line 8, in <module>
    sys.exit(cli())
  File "/home/lucky/miniconda3/envs/npc-engine/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/lucky/miniconda3/envs/npc-engine/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/lucky/miniconda3/envs/npc-engine/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/lucky/miniconda3/envs/npc-engine/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/lucky/miniconda3/envs/npc-engine/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/lucky/miniconda3/envs/npc-engine/lib/python3.8/site-packages/npc_engine/cli.py", line 78, in run_command
    run(port, start_all, models_path, http, host)
  File "/home/lucky/miniconda3/envs/npc-engine/lib/python3.8/site-packages/npc_engine/cli.py", line 93, in run
    server = ZMQServer(context, control_service, metadata_manager, start_all)
  File "/home/lucky/miniconda3/envs/npc-engine/lib/python3.8/site-packages/npc_engine/server/server.py", line 115, in __init__
    super().__init__(zmq_context, service_manager, metadata, start_services)
  File "/home/lucky/miniconda3/envs/npc-engine/lib/python3.8/site-packages/npc_engine/server/server.py", line 44, in __init__
    self.socket_ipc.bind(build_ipc_uri("self"))
  File "/home/lucky/miniconda3/envs/npc-engine/lib/python3.8/site-packages/zmq/sugar/socket.py", line 214, in bind
    super().bind(addr)
  File "zmq/backend/cython/socket.pyx", line 540, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 28, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Permission denied

**Comment by eublefar** [comment]
Could you please check permissions on the folder printed out by this command? Does npc-engine process has access to this folder?
```bash
python -c "import os, appdirs; print(os.path.join(appdirs.user_cache_dir('npc-engine'), 'self'))"
```

**Comment by ghost** [comment]
total 0
d????????? ? ? ? ?            ? .
d????????? ? ? ? ?            ? ..
s????????? ? ? ? ?            ? self

**Comment by ghost** [comment]
OK that was the problem I think ty
